POST  http://localhost:5000/api/v1/user/sign-up HTTP/1.1
Content-Type: application/json

{
    "name": "Djimi Tra",
    "email": "djamelsamili0@gmail.com",
    "password": "test123456"
}


POST http://localhost:5000/api/v1/otp/verify HTTP/1.1
Content-Type: application/json 

{
    "otp"  : "5288" , 
    "email" : "djamelsamili0@gmail.com"
}